name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  license-header-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main      # always prefer to use a revision instead of `main`.
